# Site configuration
domain: "http://www.muliba.net"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.muliba.net" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
avatar: https://s.gravatar.com/avatar/1b6b84ff3c4a172e8f0fc6b2317d76e7?s=128
about: http://muliba.u.qiniudn.com/wp-content/uploads/2012/03/3%E5%AF%B8%E9%92%B1%E5%8C%85%E7%85%A7-300x200.jpg
favicon: http://muliba.u.qiniudn.com/favicon.ico
basecss:
# Theme specific configuration
title: FancyLou's Blog
description: >
  Hi there, My name is FancyLou, Welcome to my Blog.
  I was born and raised in China.
  I'm an Android Developer.

# Contact and social media links
twitter_username: FancyLouTweet
github_username: fancylou
facebook_username:
instagram_username:
linkedin_username:

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: true

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
