safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: FancyLou's Blog
host: www.muliba.net
desc: Hi,Welcome My Blog

custom:
    category:
        default: Default Category
        another: Android Category
    categories:
      - name:  default
        title: Default Category

      - name:  android
        title: Android Category

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: FancyLou
        email: Fancylou@outlook.com
        disqus: muliba              # Disqus缩略标识
        gcse: 007212716797013267673:irm0hfnyso4     # Google自定义搜索标识ID
        github: fancylou                 # GitHub账号
        gravatar: 72c53db1893a7706bcec817d09ec1645  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
